accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('profile/<int:id>/', profile, name='profile')
]

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('story/<int:id>/', story_detail, name='story_detail'),
    path('about/', about, name='about'),
    path('stories', stories, name='stories'),
    path('recipes', recipes, name='recipes'),
    path('recipe/<int:id>/', recipe_detail, name='recipe_detail'),
    path('contact', contact, name='contact'),
]

foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='images/' ,null=True, blank=True)
    info = models.TextField()

core/models.py
from django.db import models

class Story(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    category = models.ForeignKey('Category', related_name='stories', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', related_name='stories')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title
    
class Tag(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Comment(models.Model):
    # user
    text = models.TextField()

    def __str__(self):
        return self.text

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image', 'info',]
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'image': forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
            'info': forms.Textarea(attrs={'class':'form-control','placeholder':'Info'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
        }

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
        }

core/forms.py
from django import forms
from core.models import *

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Your Name'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Your Email'}),
            'subject': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Subject'}),
            'message': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Message'}),
        }

accounts/views.py
from django.shortcuts import render
from accounts.models import User
from django.views.generic import CreateView
from accounts.forms import *
from django.contrib.auth.views import LoginView

class RegisterView(CreateView):
    template_name = "register.html"
    model = User
    form_class = RegisterForm
    success_url = '/'

class Login(LoginView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = '/'
    model = User

def profile(request, id):
    user = User.objects.get(id=id)
    context = {
        'user':user,
    }
    return render(request, 'user-profile.html', context)

core/views.py
from django.shortcuts import render, redirect
from core.models import *
from core.forms import *

def home(request):
    stories = Story.objects.order_by('-id')[:4]
    last_story = stories.first()
    categories = Category.objects.all()
    holiday = Story.objects.filter(category__title='Holiday')
    context = {
        'stories': stories,
        'last_story': last_story,
        'categories': categories,
        'holiday': holiday
    }
    return render(request, 'index.html', context)


def story_detail(request, id):
    story = Story.objects.get(id=id)
    categories = Category.objects.all()
    recents = Story.objects.order_by('-id')[:2]
    tags = Tag.objects.all()
    context = {
        'data': story,
        'categories': categories,
        'recents': recents,
        'tags': tags
    }
    return render(request, 'single.html', context)

def about(request):
    return render(request, 'about.html')

def stories(request):
    tag = request.GET.get("tag")
    search = request.GET.get('search')
    cat = request.GET.get('cat')
    stories = Story.objects.order_by('-id')
    if search:
        stories = stories.filter(title__icontains=search)
    if cat:
        stories = stories.filter(category__title=cat)
    if tag:
        stories = stories.filter(tags__title=tag)
    categories = Category.objects.all()
    
    context = {
        'stories': stories,
        'categories':categories,
    }
    return render(request, 'stories.html', context)


def recipes(request):
    search = request.GET.get('search')
    cat = request.GET.get('cat')
    recipes = Recipe.objects.order_by('-id')
    categories = Category.objects.all()
    stories = Story.objects.order_by('-id')
    if search:
        recipes = recipes.filter(title__icontains=search)
    if cat:
        recipes = recipes.filter(category__title=cat)
    context = {
        'recipes':recipes,
        'categories':categories,
        'stories': stories,
    }
    return render(request, 'recipes.html', context)

def recipe_detail(request, id):
    recipe = Recipe.objects.get(id=id)
    categories = Category.objects.all()
    recents =  Recipe.objects.order_by('-id')[:2]
    tags = Tag.objects.all()
    context = {
        'data': recipe,
        'categories': categories,
        'recents': recents,
        'tags': tags
    }
    return render(request, 'recipe.html', context)

def contact(request):
     if request.method == 'POST':
          form = ContactForm(request.POST)
          if form.is_valid():
               form.save()
               return redirect('core:home')
     form = ContactForm()
     return render(request, 'contact.html', {"form":form})

core/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home' %}">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'core:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'core:about' %}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{% url 'core:stories' %}" class="nav-link">Stories</a></li>
                <li class="nav-item"><a href="{% url 'core:recipes' %}" class="nav-link">Recipes</a></li>
                <li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link">Contact</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' request.user.id %}" class="btn btn-black px-3 px-md-4 py-3">{{request.user.username}}</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Login</a></li>
                <li><a href="{% url 'accounts:register' %}" class="btn btn-black px-3 px-md-4 py-3">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

core/templates/recipes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Recipes</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'core:home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Recipes <i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">

                    {% for recipe in recipes %}
                    <div class="col-md-6 col-lg-12 ftco-animate">
                        <div class="blog-entry d-lg-flex">
                            <div class="half">
                                <a href="{% url 'core:recipe_detail' recipe.id%}" class="img d-flex align-items-end"
                                   style="background-image: url({{ recipe.image.url }});">
                                    <div class="overlay"></div>
                                </a>
                            </div>
                            <div class="text px-md-4 px-lg-5 half pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{ recipe.category }}</span><span class="ml-auto pl-3">{{recipe.date | date:"M d, Y"}}</span>
                                </p>
                                <h3><a href="{% url 'core:recipe_detail' recipe.id%}">{{ recipe.title }}</a></h3>
                                <p>{{ recipe.description }}</p>
                                <p class="mb-0"><a href="{% url 'core:recipe_detail' recipe.id%}" class="btn btn-primary">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                <li><a href="#">&lt;</a></li>
                                <li class="active"><span>1</span></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#">&gt;</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="images/author.jpg" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>Cathy Deon</strong>, behind the word mountains, far from the
                                countries Vokalia and Consonantia, there live the blind texts. Separated they live in
                                Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                        </div>
                    </div>
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input name="search" type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box categories text-center ftco-animate">
                        <h2 class="heading mb-4">Categories</h2>
                        <ul class="category-image">
                            {% for category in categories %}
                            <li>
                                <a href="{% url 'core:stories' %}?cat={{category.title}}" class="img d-flex align-items-center justify-content-center text-center"
                                   style="background-image: url({{ category.image.url }});">
                                    <div class="text">
                                        <h3>{{category.title}}</h3>
                                    </div>
                                </a>
                            </li>
                            {% endfor %}
                      
                        
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

core/templates/single.html
{% extends 'base.html' %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({{data.image.url}});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{data.title}}</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'core:home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>{{data.title}}<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 order-lg-last ftco-animate">
                <h2 class="mb-3">{{data.description}}</h2>
                <p>{{data.text}}</p>
                <p>
                    <img src="{{data.image.url}}" alt="" class="img-fluid">
                </p>
               
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in data.tags.all %}
                        <a href="{% url 'core:stories' %}?tag={{tag.title}}" class="tag-cloud-link">{{tag.title}}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>George Washington</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5">6 Comments</h3>
                    <ul class="comment-list">
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>

                        <li class="comment">
                            <div class="vcard bio">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>

                            <ul class="children">
                                <li class="comment">
                                    <div class="vcard bio">
                                        <img src="images/person_1.jpg" alt="Image placeholder">
                                    </div>
                                    <div class="comment-body">
                                        <h3>John Doe</h3>
                                        <div class="meta">October 03, 2018 at 2:21pm</div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem
                                            laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe
                                            enim sapiente iste iure! Quam voluptas earum impedit necessitatibus,
                                            nihil?</p>
                                        <p><a href="#" class="reply">Reply</a></p>
                                    </div>


                                    <ul class="children">
                                        <li class="comment">
                                            <div class="vcard bio">
                                                <img src="images/person_1.jpg" alt="Image placeholder">
                                            </div>
                                            <div class="comment-body">
                                                <h3>John Doe</h3>
                                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur
                                                    quidem laborum necessitatibus, ipsam impedit vitae autem, eum
                                                    officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum
                                                    impedit necessitatibus, nihil?</p>
                                                <p><a href="#" class="reply">Reply</a></p>
                                            </div>

                                            <ul class="children">
                                                <li class="comment">
                                                    <div class="vcard bio">
                                                        <img src="images/person_1.jpg" alt="Image placeholder">
                                                    </div>
                                                    <div class="comment-body">
                                                        <h3>John Doe</h3>
                                                        <div class="meta">October 03, 2018 at 2:21pm</div>
                                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                                            Pariatur quidem laborum necessitatibus, ipsam impedit vitae
                                                            autem, eum officia, fugiat saepe enim sapiente iste iure!
                                                            Quam voluptas earum impedit necessitatibus, nihil?</p>
                                                        <p><a href="#" class="reply">Reply</a></p>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li class="comment">
                            <div class="vcard bio">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                    </ul>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form action="#" class="p-5 bg-light">
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <input type="url" class="form-control" id="website">
                            </div>

                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>

                        </form>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <ul class="categories">
                        <h3 class="heading mb-4">Categories</h3>
                        {% for category in categories %}
                        <li><a href="{% url 'core:stories' %}?cat={{category.title}}">{{category.title}}</a></li>
                        {% endfor %}
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Recent Blog</h3>
                    {% for rc in recents %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{rc.image.url}});"></a>
                        <div class="text">
                            <h3><a href="{% url 'core:story_detail' rc.id%}">{{rc.title}}</a></h3>
                            <div class="meta">
                                <div><a href="{% url 'core:story_detail' rc.id%}"><span class="icon-calendar"></span> {{rc.date | date:"F d, Y"}}</a></div>
                                <div><a href="{% url 'core:story_detail' rc.id%}"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="{% url 'core:story_detail' rc.id%}"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                        <a href="{% url 'core:stories' %}?tag={{tag.title}}" class="tag-cloud-link">{{tag.title}}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->

<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}